"""
SETTINGS MODULE
"""


from decouple import config


PATH_TO_CONTENT = config('PATH_TO_CONTENT')
PATH_TO_DJANGO_APPS = config('PATH_TO_DJANGO_APPS')
PATH_TO_DJANGO_PROJECT_SETTINGS = config('PATH_TO_DJANGO_PROJECT_SETTINGS')
